server:
  port: 8080

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]

  application:
    name: getway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Auth Service
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
              filters:
                - name: ApiResponse

        # # Order Service
        # - id: order-service
        #   uri: lb://order-service
        #   predicates:
        #     - Path=/api/orders/**

        # # Product Service
        # - id: product-service
        #   uri: lb://product-service
        #   predicates:
        #     - Path=/api/products/**
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true

  instance:
    prefer-ip-address: true
    # Rút ngắn thời gian chờ để Eureka bỏ instance đã tắt nhanh hơn.
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

app:
  jwt:
    public-key: ${JWT_PUBLIC_KEY}

# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info
